### ISSUE TITLE
epic: Cortex supports preset configuration list

### ISSUE THREAD

**Issue by Van-QA** [janhq/cortex#617]
**Problem:**
Users are unable to use imported GGUFs effectively as they all use default templates and parameters, requiring individual editing of each model's model.json file.
https://discord.com/channels/1107178041848909847/1244886808979046452

**Success Criteria:**

- [x] 1. Enable automatic updating of the model.yaml file when users change model parameters during runtime. 
`Model.yaml files store model configurations. If users modify these configurations during runtime, the files should be updated accordingly.`

- [x] https://github.com/janhq/cortex/issues/616
`2. Ensure each model has its own model.yaml file, located in the same folder as the GGUF binary. Similar to the current model's folder structure `

- [x] janhq/jan#2960
`3. Attempt to extract metadata from a GGUF file.`

- [ ] 4. Implement a list of popular template configurations for any models that users import. janhq/jan#2958
`Missing configurations will load with fallback presets. The configurations list refers to a pre-populated list and local cache of model + thread settings with memorable names, allowing users to choose from during the import process.`

- [x] 5. Allow users to add their own custom templates. `Users should have the ability to add their own custom templates, maybe r‌‌eusing from available model that they configur‌ated`

**Comment by louis-jan** [comment]
For number 2, there is no need to put the YAML file under the model folder, since symlink support is available; all YAML files are located at /models.

**Comment by louis-jan** [comment]
Do you want to take the 4 @Van-QA?

**Comment by Van-QA** [comment]
> Do you want to take the 4 @Van-QA?

I will work with @hahuyhoang411 on this, thank @louis-jan

**Comment by Van-QA** [comment]
Llama 3:
prompt_template: "<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\n{system_message}<|eot_id|><|start_header_id|>user<|end_header_id|>\n\n{prompt}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n"

ChatML:
prompt_template: "<|im_start|>system\n{system_message}<|im_end|>\n<|im_start|>user\n{prompt}<|im_end|>\n<|im_start|>assistant"

Alpaca:
prompt_template: "{system_message}\n### Instruction: {prompt}\n### Response:"

Vicuna:
prompt_template: "<｜begin_of_sentence｜>{system_prompt}\n\nUser: {prompt}\n\nAssistant:"
